### ISSUE TITLE
Add more options for the auto plot method

### ISSUE THREAD

**Issue by smouksassi** [certara/tidyvpc#13]
need to make the alpha a function parameter
https://github.com/certara/tidyvpc/blob/master/R/plot.R#L50

need to make points size and transparency adjustable as well
https://github.com/certara/tidyvpc/blob/master/R/plot.R#L129
https://github.com/certara/tidyvpc/blob/master/R/plot.R#L133

(Also need to fix and apply for the binless, points and areas)
https://github.com/certara/tidyvpc/blob/master/R/plot.R#L174

**Comment by certara-jcraig** [comment]
Hi @smouksassi the enhancements proposed have been implemented, please install latest dev version to test.
