### ISSUE TITLE
add missing classint styles

### ISSUE THREAD

**Issue by smouksassi** [certara/tidyvpc#19]
currently we have: 
known.classInt.styles <- c("fixed", "sd", "equal", "pretty", "quantile",
                               "kmeans", "hclust", "bclust", "fisher", "jenks", "dpih")

there is headtails, maximum and box that might be relevant for other  styles of plots

https://github.com/r-spatial/classInt/blob/bee8f588d71a3a92d62677720bd89facd91dd32c/man/classIntervals.Rd#L69

also update 
Certara.VPCResults UI

**Comment by certara-jcraig** [comment]
Thanks @smouksassi - implemented in the following PR: https://github.com/certara/tidyvpc/pull/23
Closing issue.

**Comment by smouksassi** [comment]
also need these options in VPC.results
