### ISSUE TITLE
Request: Ability to handle only 2 qpred values (e.g. remove lower bound from vpc plot)

### ISSUE THREAD

**Issue by pseastham-certara** [certara/tidyvpc#24]
Currently the way to handle wanting to remove the lower bound is to have 

vpcstats(qpred = c(NA, 0.5, 0.95))

which works in that it removes the 5% line/ribbon from the vpc plot. The remaining issue is that then the legend contains "NA" which is ugly.

This seems like a big ask because I see that vpcstats requires a length-3 vector in many places but it seems like it would be useful to add this functionality.

**Comment by smouksassi** [comment]
Hi Patrick can you give more context on your use case ?

**Comment by pseastham-certara** [comment]
Hi Samer, we wanted to produce a vpc plot with only 50th and 95th percentile lines shown (basically remove the 5th percentile line). However, if we set "qpred=c(0.5, 0.95)" there is an error. A workaround is to have qpred=c(NA, 0.5, 0.95), which produces the desired plot, except for the legend then has an "NA" label. I unfortunately no longer have a screenshot of what it looks like.

**Comment by smouksassi** [comment]
why not repeat the quantile? I know it is not ideal but can be a good compromise

``` r
library(magrittr)
library(ggplot2)
library(tidyvpc)
#> tidyvpc is part of Certara.R!
#> Follow the link below to learn more about PMx R package development at Certara.
#> https://certara.github.io/R-Certara/
obs_data <- tidyvpc::obs_data[MDV == 0]
sim_data <- tidyvpc::sim_data[MDV == 0]


# Binning Method on x-variable (NTIME)
vpc <- observed(obs_data, x=TIME, y=DV) %>%
  simulated(sim_data, y=DV) %>%
  stratify(~ STUDY) %>%
  binning(bin = NTIME) %>%
  vpcstats(qpred = c( 0.25,0.5,0.5))

plot(vpc)
```

![](https://i.imgur.com/Gt19I16.png)

<sup>Created on 2023-04-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by pseastham-certara** [comment]
Oh that's great! I did not consider repeating it. That's perfectly acceptable, thank you!

**Comment by certara-jcraig** [comment]
Closing issue as @smouksassi has proposed a viable workaround.
