### ISSUE TITLE
Documentation Request: Vignette with nlmixr2

### ISSUE THREAD

**Issue by billdenney** [certara/tidyvpc#27]
I recently learned of this package, and it looks like it will be very helpful for my workflow!

I wonder if you would be interested in adding a vignette for how to use `tidyvpc` with `nlmixr2`?  I do most of my work in nlmixr2 now, and I would find a recipe for how to use nlmixr2 with tidyvpc to be helpful.  If of interest, I'd be happy to try to write it (though since I'm learning the package, I'd appreciate a close review of any PR that I make to ensure that I'm using the package as intended).

**Comment by mattfidler** [comment]
I agree this would be quite helpful!

**Comment by certara-jcraig** [comment]
Thanks for the suggestion, @billdenney and @mattfidler - I'm glad that you are finding the package useful and I also think it'd  be helpful to include a nlmixr2 + tidyvpc vignette. I'll keep an eye out for your PR and I know @smouksassi will be happy to review as well. Looking forward to your contribution here!
